apiVersion: v1
kind: ImageStream
metadata:
  name: znc
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/tnozicka/znc:latest
    importPolicy:
      scheduled: true
